"""Reporter Agent — consolidates the Admin and User agent logs into REPORT.md.

Only summarizes what the other agents recorded; invents nothing.
"""
import json
import os
from collections import OrderedDict
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS_DIR = os.path.join(HERE, "..", "results")
REPORT_PATH = os.path.join(HERE, "..", "REPORT.md")


def load(name):
    path = os.path.join(RESULTS_DIR, name)
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def main():
    entries = load("user_results.json") + load("admin_results.json")
    if not entries:
        raise SystemExit("no agent results found — run the agents first")

    total = len(entries)
    passed = sum(1 for e in entries if e["pass"])
    failed = [e for e in entries if not e["pass"]]

    by_feature = OrderedDict()
    for e in entries:
        by_feature.setdefault(e["feature"], []).append(e)

    lines = []
    lines.append("# ResQueue — Consolidated Test Report")
    lines.append("")
    lines.append(f"*Generated by the Reporter Agent on "
                 f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} "
                 f"from Admin Agent and User Agent logs.*")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Tests executed:** {total}")
    lines.append(f"- **Passed:** {passed}")
    lines.append(f"- **Failed:** {total - passed}")
    verdict = "ALL TESTS PASSED" if not failed else f"{len(failed)} FAILURE(S) FOUND"
    lines.append(f"- **Verdict:** {verdict}")
    lines.append("")

    if failed:
        lines.append("## Failures & Inconsistencies")
        lines.append("")
        for e in failed:
            lines.append(f"- **{e['action']}** ({e['agent']}) — expected: "
                         f"{e['expected']}; observed: {e['observed']}")
        lines.append("")
    else:
        lines.append("## Inconsistencies / Bugs")
        lines.append("")
        lines.append("None observed. Every expected behavior — including error "
                     "handling, visibility rules, privilege enforcement and "
                     "propagation of admin actions — matched the observed behavior.")
        lines.append("")

    lines.append("## Detailed Results")
    lines.append("")
    for feature, tests in by_feature.items():
        f_pass = sum(1 for t in tests if t["pass"])
        lines.append(f"### {feature} ({f_pass}/{len(tests)} passed)")
        lines.append("")
        lines.append("| Test | Agent | Expected | Observed | Result |")
        lines.append("|---|---|---|---|---|")
        for t in tests:
            obs = t["observed"].replace("|", "\\|").replace("\n", " ")
            if len(obs) > 140:
                obs = obs[:140] + "…"
            exp = t["expected"].replace("|", "\\|")
            mark = "✅ Pass" if t["pass"] else "❌ Fail"
            lines.append(f"| {t['action']} | {t['agent']} | {exp} | {obs} | {mark} |")
        lines.append("")

    lines.append("## Recommendations")
    lines.append("")
    if not failed:
        lines.append("- The system is behaving to spec for all tested workflows. "
                      "For production use, replace the simulated outbox with a real "
                      "email provider, add rate limiting on login/verify, and add "
                      "token expiry.")
    else:
        lines.append("- Address the failures listed above before release.")
    lines.append("")

    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[Reporter Agent] {passed}/{total} passed -> {REPORT_PATH}")


if __name__ == "__main__":
    main()
