"""Render the agent result logs into a styled HTML report (for publishing)."""
import html
import json
import os
import sys
from collections import OrderedDict
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS_DIR = os.path.join(HERE, "..", "results")


def load(name):
    with open(os.path.join(RESULTS_DIR, name), encoding="utf-8") as f:
        return json.load(f)


entries = load("user_results.json") + load("admin_results.json")
total = len(entries)
passed = sum(1 for e in entries if e["pass"])
failed = [e for e in entries if not e["pass"]]
agents = OrderedDict()
for e in entries:
    agents.setdefault(e["agent"], []).append(e)
by_feature = OrderedDict()
for e in entries:
    by_feature.setdefault(e["feature"], []).append(e)

CSS = """
:root{
  --paper:#F6F8FA; --card:#FFFFFF; --ink:#1C2733; --muted:#5C6B7A;
  --line:#DCE3EA; --accent:#12406B; --accent-soft:#E8EFF6;
  --pass:#1E7A46; --pass-bg:#E7F3EC; --fail:#B3383E; --fail-bg:#F9E9EA;
  --mono:ui-monospace,'Cascadia Code',Consolas,monospace;
}
:root:not([data-theme="light"]){}
@media (prefers-color-scheme: dark){
  :root:not([data-theme="light"]){
    --paper:#12181F; --card:#1A222B; --ink:#E4EBF2; --muted:#93A3B2;
    --line:#2C3843; --accent:#7FB3E0; --accent-soft:#1F2E3C;
    --pass:#5FC98E; --pass-bg:#16301F; --fail:#E58B90; --fail-bg:#3A2022;
  }
}
:root[data-theme="dark"]{
  --paper:#12181F; --card:#1A222B; --ink:#E4EBF2; --muted:#93A3B2;
  --line:#2C3843; --accent:#7FB3E0; --accent-soft:#1F2E3C;
  --pass:#5FC98E; --pass-bg:#16301F; --fail:#E58B90; --fail-bg:#3A2022;
}
*{box-sizing:border-box}
body{margin:0;background:var(--paper);color:var(--ink);
  font:16px/1.55 system-ui,'Segoe UI',sans-serif}
.wrap{max-width:920px;margin:0 auto;padding:40px 20px 64px;
  display:flex;flex-direction:column;gap:28px}
.eyebrow{font:600 12px/1 var(--mono);letter-spacing:.14em;text-transform:uppercase;
  color:var(--accent);margin:0 0 10px}
h1{font-size:30px;line-height:1.2;margin:0;text-wrap:balance}
.meta{color:var(--muted);font-size:14px;margin-top:8px}
.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}
.stat{background:var(--card);border:1px solid var(--line);border-radius:8px;
  padding:14px 16px}
.stat .n{font:600 26px/1.2 var(--mono);font-variant-numeric:tabular-nums}
.stat .l{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:var(--muted)}
.stat.ok .n{color:var(--pass)} .stat.bad .n{color:var(--fail)}
.verdict{background:var(--pass-bg);color:var(--pass);border:1px solid var(--pass);
  border-radius:8px;padding:12px 16px;font-weight:600}
.verdict.bad{background:var(--fail-bg);color:var(--fail);border-color:var(--fail)}
section h2{font-size:19px;margin:0 0 4px;padding-top:8px}
section .sub{color:var(--muted);font-size:14px;margin:0 0 12px}
.tblwrap{overflow-x:auto;background:var(--card);border:1px solid var(--line);
  border-radius:8px}
table{border-collapse:collapse;width:100%;font-size:14px;min-width:640px}
th{font:600 11px/1.3 var(--mono);letter-spacing:.1em;text-transform:uppercase;
  text-align:left;color:var(--muted);padding:10px 14px;border-bottom:1px solid var(--line)}
td{padding:10px 14px;border-bottom:1px solid var(--line);vertical-align:top}
tr:last-child td{border-bottom:0}
td.obs{font-family:var(--mono);font-size:12.5px;color:var(--muted);max-width:340px}
.pill{display:inline-block;font:600 12px/1 var(--mono);padding:5px 9px;border-radius:99px}
.pill.ok{background:var(--pass-bg);color:var(--pass)}
.pill.bad{background:var(--fail-bg);color:var(--fail)}
.agent{font-size:12px;color:var(--muted);white-space:nowrap}
.note{background:var(--accent-soft);border:1px solid var(--line);border-radius:8px;
  padding:14px 16px;font-size:14px}
.note b{color:var(--accent)}
footer{color:var(--muted);font-size:13px;border-top:1px solid var(--line);padding-top:16px}
"""

parts = []
parts.append(f"<title>ResQueue Test Report</title><style>{CSS}</style>")
parts.append('<div class="wrap">')
parts.append('<header><p class="eyebrow">ResQueue &middot; Multi-agent validation</p>'
             '<h1>Consolidated Test Report</h1>'
             f'<p class="meta">Generated by the Reporter Agent on '
             f'{datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")} from live API runs '
             f'of the Admin Agent and User Agent against resqueue_server.py '
             f'(Flask + SQLite, http://127.0.0.1:8765).</p></header>')

agent_tiles = "".join(
    f'<div class="stat"><div class="n">{sum(1 for t in ts if t["pass"])}/{len(ts)}</div>'
    f'<div class="l">{html.escape(a)}</div></div>'
    for a, ts in agents.items())
parts.append(f'''<div class="stats">
<div class="stat"><div class="n">{total}</div><div class="l">Tests executed</div></div>
<div class="stat ok"><div class="n">{passed}</div><div class="l">Passed</div></div>
<div class="stat{" bad" if failed else ""}"><div class="n">{total - passed}</div><div class="l">Failed</div></div>
{agent_tiles}</div>''')

if failed:
    items = "".join(f"<li><b>{html.escape(e['action'])}</b> — expected {html.escape(e['expected'])}; "
                    f"observed {html.escape(e['observed'])}</li>" for e in failed)
    parts.append(f'<div class="verdict bad">{len(failed)} failure(s) found<ul>{items}</ul></div>')
else:
    parts.append(f'<div class="verdict">All {total} behaviors matched their specification — '
                 'including error handling, visibility rules, privilege enforcement, and '
                 'propagation of admin actions to live sessions.</div>')

for feature, tests in by_feature.items():
    f_pass = sum(1 for t in tests if t["pass"])
    rows = []
    for t in tests:
        mark = '<span class="pill ok">PASS</span>' if t["pass"] else '<span class="pill bad">FAIL</span>'
        obs = t["observed"]
        if len(obs) > 160:
            obs = obs[:160] + "…"
        rows.append(f"<tr><td>{html.escape(t['action'])}</td>"
                    f"<td class='agent'>{html.escape(t['agent'])}</td>"
                    f"<td>{html.escape(t['expected'])}</td>"
                    f"<td class='obs'>{html.escape(obs)}</td><td>{mark}</td></tr>")
    parts.append(f'''<section><h2>{html.escape(feature)}</h2>
<p class="sub">{f_pass} of {len(tests)} passed</p>
<div class="tblwrap"><table><thead><tr><th>Test</th><th>Agent</th><th>Expected</th>
<th>Observed</th><th>Result</th></tr></thead><tbody>{"".join(rows)}</tbody></table></div></section>''')

parts.append('<div class="note"><b>Recommendations.</b> The system behaves to spec for every '
             'tested workflow. Before production use: replace the simulated email outbox with a '
             'real provider, add rate limiting on login and verification attempts, and give '
             'session tokens an expiry.</div>')
parts.append('<footer>Reporter Agent consolidation of results/user_results.json and '
             'results/admin_results.json &middot; no results were invented or altered.</footer>')
parts.append('</div>')

out = sys.argv[1]
with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(parts))
print("wrote", out)
